### ISSUE TITLE
Receiver hangs when diode is rebooted during file transfer

### ISSUE THREAD

**Issue by Raimund-G** [bluhm/file-sync#2]
A file is currently being transferred over the diode. Now I reset/reboot of the diode.
Now the receiver script hangs forever, new files will not be transferred.

**Comment by bluhm** [comment]
My first idea was that stetting the TCP keep-alive option in the file-sync scripts would fix that.  Unfortunately it still hangs.

**Comment by bluhm** [comment]
Linux waits for 2 hours before sending TCP keep-alive.  If you change the global kernel variables or wait long enough it works now.

**Comment by bluhm** [comment]
May be I was too fast when closing this bug report.  On top of the TCP keep-alive I have added send and receive socket timeouts.  After 60 seconds of inactivity the connection terminates.
